---

- name: create new password file if it does not exist
  copy:
    dest: /tmp/password
    content: "{{ lookup('password', '/dev/null') }}"
    mode: 0600
    force: no
  when: inventory_hostname == groups['password-provider'][0]

- name: register database_password variable
  slurp:
    src:  /tmp/password
  register: database_password_slurp
  delegate_to: "{{ groups['password-provider'] | first }}"
  check_mode: no

- name: Distribute the password
  copy:
    content: "{{ database_password_slurp['content'] | b64decode | trim }}"
    dest: /tmp/password
